// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var FirebaseAdmin = require("firebase-admin");

function app(prim) {
  FirebaseAdmin.initializeApp();
  return /* () */0;
}

exports.app = app;
/* firebase-admin Not a pure module */
